# Generated by Django 2.2.5 on 2021-08-07 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='profile_pics')),
                ('about_details', models.TextField(max_length=10000, verbose_name='Put here About Deatils')),
                ('mission_title', models.TextField(max_length=1000, verbose_name='write here your mission title')),
                ('mission_details', models.TextField(max_length=10000, verbose_name='write here mission details')),
            ],
        ),
        migrations.CreateModel(
            name='Bss_syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus', verbose_name='Upload here any file')),
            ],
        ),
        migrations.CreateModel(
            name='ChairmanMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmnent_intro', models.TextField(max_length=4000, verbose_name='Put here department introduction')),
                ('chairman_name', models.TextField(max_length=120, verbose_name='write here chariman Name')),
                ('chairman_role', models.TextField(max_length=300, verbose_name='write hete chairman Role detials')),
                ('chairman_img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_image', models.ImageField(upload_to='gallery', verbose_name='image size should be')),
                ('lab_details', models.TextField(max_length=10000, verbose_name='write here seminar details')),
            ],
        ),
        migrations.CreateModel(
            name='Crime_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_image', models.ImageField(upload_to='gallery', verbose_name='image size should be')),
                ('lab_details', models.TextField(max_length=10000, verbose_name='write here seminar details')),
            ],
        ),
        migrations.CreateModel(
            name='Eventlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_title', models.CharField(max_length=333, verbose_name='Put a Event title here')),
                ('events_img', models.ImageField(upload_to='profile_pics')),
                ('events_date', models.CharField(max_length=120, verbose_name='Put here static date')),
            ],
        ),
        migrations.CreateModel(
            name='Facilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilites_title', models.TextField(max_length=700, verbose_name='Put your facilites title here')),
                ('facilites_img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_one', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_two', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_three', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_four', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_five', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_six', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_seven', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
                ('img_eight', models.ImageField(upload_to='gallery', verbose_name='Drop a Image')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderAndFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(max_length=100, verbose_name='Facebook Link')),
                ('twitter_link', models.URLField(max_length=100, verbose_name='Twitter Link')),
                ('google_link', models.URLField(max_length=100, verbose_name='Google Plus Link')),
                ('linkedin_link', models.URLField(max_length=100, verbose_name='LinkedIn Link')),
                ('instagram_link', models.URLField(max_length=100, verbose_name='Instagram Link')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_one', models.ImageField(upload_to='profile_pics')),
                ('slider_two', models.ImageField(upload_to='profile_pics')),
                ('slider_three', models.ImageField(upload_to='profile_pics')),
            ],
            options={
                'ordering': ['-slider_one'],
            },
        ),
        migrations.CreateModel(
            name='Mphil_phd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus', verbose_name='Upload here any file')),
            ],
        ),
        migrations.CreateModel(
            name='Mss_syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus', verbose_name='Upload here any file')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=400)),
                ('news_file', models.FileField(upload_to='Pulication')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.TextField(blank=True, max_length=400, verbose_name='put here program Heading')),
                ('program_details', models.TextField(blank=True, max_length=1000, verbose_name='put here program Heading')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.TextField(blank=True, max_length=1000, verbose_name='Write here research title')),
                ('research_details', models.TextField(blank=True, max_length=10000, verbose_name='Write here research details')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_image', models.ImageField(upload_to='gallery', verbose_name='image size should be')),
                ('seminar_details', models.TextField(max_length=10000, verbose_name='write here seminar details')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=212, verbose_name='Put a teacher name')),
                ('teacher_img', models.ImageField(upload_to='profile_pics')),
                ('teacher_designation', models.TextField(max_length=400, verbose_name='Put a teacher designation here')),
                ('teacher_fb', models.URLField(verbose_name='Put here teacher Facebook id link')),
                ('teacher_twitter', models.URLField(verbose_name='Put here teacher twitter id link')),
                ('teacher_linkldn', models.URLField(verbose_name='Put here teacher Linkldn id link')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.TextField(max_length=400, verbose_name='write here Event tile')),
                ('event_date', models.CharField(max_length=20, verbose_name='put here date')),
                ('event_details', models.TextField(max_length=1000, verbose_name='Put here event details')),
                ('event_img', models.ImageField(upload_to='gallery')),
                ('event_file', models.FileField(upload_to='event_docx')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_subjetct', models.TextField(max_length=600, verbose_name='Put which subject are you taken')),
                ('research_interest', models.TextField(max_length=700, verbose_name='put here your reaserach and interest')),
                ('teacher_cv', models.FileField(upload_to='Cv')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Criminology_App.TeacherList')),
            ],
        ),
        migrations.CreateModel(
            name='Facilites_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=30000, verbose_name='Put here facilites details')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Criminology_App.Facilite')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_details', models.TextField(max_length=3000, verbose_name='Put a event details here')),
                ('event_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Criminology_App.Eventlist')),
            ],
        ),
    ]
