# Generated by Django 3.2 on 2021-08-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPublication',
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='event_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='put here date'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='event_details',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Put here event details'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='event_file',
            field=models.FileField(blank=True, upload_to='event_docx'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='event_title',
            field=models.TextField(blank=True, max_length=400, verbose_name='write here Event tile'),
        ),
    ]
