# Generated by Django 2.2.5 on 2021-07-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_detail',
            options={},
        ),
    ]
