# Generated by Django 2.2.5 on 2021-08-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=400)),
                ('news_file', models.FileField(upload_to='Pulication')),
            ],
        ),
        migrations.DeleteModel(
            name='NewEvent',
        ),
    ]
