# Generated by Django 2.2.5 on 2021-07-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Past_Eventlist',
        ),
        migrations.AlterModelOptions(
            name='teacher_detail',
            options={'ordering': ['teacher_name']},
        ),
    ]
