# Generated by Django 2.2.5 on 2021-07-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_details', models.TextField(max_length=3000, verbose_name='Put a event details here')),
                ('event_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Criminology_App.Eventlist')),
            ],
        ),
    ]
