# Generated by Django 2.2.5 on 2021-07-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0002_pastevent_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastEvent_Detail',
        ),
    ]
