# Generated by Django 2.2.5 on 2021-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0002_auto_20210714_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_project',
            name='research_project_heading',
        ),
        migrations.AddField(
            model_name='about',
            name='mission_title',
            field=models.TextField(default=1, max_length=1000, verbose_name='write here your mission title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about_details',
            field=models.TextField(max_length=10000, verbose_name='Put here About Deatils'),
        ),
    ]
