# Generated by Django 2.2.5 on 2021-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0002_auto_20210724_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderAndFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(max_length=100, verbose_name='Facebook Link')),
                ('twitter_link', models.URLField(max_length=100, verbose_name='Twitter Link')),
                ('google_link', models.URLField(max_length=100, verbose_name='Google Plus Link')),
                ('linkedin_link', models.URLField(max_length=100, verbose_name='LinkedIn Link')),
                ('instagram_link', models.URLField(max_length=100, verbose_name='Instagram Link')),
            ],
        ),
    ]
