# Generated by Django 2.2.5 on 2021-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0003_auto_20210714_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission_details',
            field=models.TextField(default=1, max_length=10000, verbose_name='write here mission details'),
            preserve_default=False,
        ),
    ]
