# Generated by Django 2.2.5 on 2021-08-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0003_secondevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairmanmessage',
            name='chairman_role',
            field=models.TextField(blank=True, max_length=300, verbose_name='write hete chairman Role detials'),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='events_details',
            field=models.TextField(max_length=300000, verbose_name='Put a event details here'),
        ),
    ]
