# Generated by Django 2.2.5 on 2021-07-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0004_about_mission_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research_Project',
        ),
        migrations.DeleteModel(
            name='Research_Publication',
        ),
    ]
