# Generated by Django 2.2.5 on 2021-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0005_auto_20210714_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.TextField(max_length=1000, verbose_name='Write here research title')),
                ('research_details', models.TextField(max_length=10000, verbose_name='Write here research details')),
                ('feature_img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Vision_Goals',
        ),
    ]
