# Generated by Django 2.2.5 on 2021-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0006_auto_20210714_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_publication',
            name='research_details',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Write here research details'),
        ),
        migrations.AlterField(
            model_name='research_publication',
            name='research_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Write here research title'),
        ),
    ]
