# Generated by Django 2.2.5 on 2021-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0007_auto_20210714_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_publication',
            name='feature_img',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
