# Generated by Django 2.2.5 on 2021-07-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0008_auto_20210714_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_publication',
            name='feature_img',
        ),
    ]
