# Generated by Django 2.2.5 on 2021-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0009_remove_research_publication_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_publication',
            name='feature_img',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
