# Generated by Django 2.2.5 on 2021-07-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0010_research_publication_feature_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_publication',
            name='feature_img',
        ),
    ]
