# Generated by Django 2.2.5 on 2021-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0013_seminar_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_image', models.ImageField(upload_to='gallery', verbose_name='image size should be')),
                ('seminar_details', models.TextField(max_length=10000, verbose_name='write here seminar details')),
            ],
        ),
    ]
