# Generated by Django 2.2.5 on 2021-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0015_auto_20210715_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_image', models.ImageField(upload_to='gallery', verbose_name='image size should be')),
                ('lab_details', models.TextField(max_length=10000, verbose_name='write here seminar details')),
            ],
        ),
    ]
