# Generated by Django 2.2.5 on 2021-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminology_App', '0016_crime_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bss_syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus', verbose_name='Upload here any file')),
            ],
        ),
        migrations.CreateModel(
            name='Mphil_phd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus', verbose_name='Upload here any file')),
            ],
        ),
        migrations.CreateModel(
            name='Mss_syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus', verbose_name='Upload here any file')),
            ],
        ),
    ]
